### ISSUE TITLE
Is the san_8w data before or after data aug?

### ISSUE THREAD

**Issue by pokemonjs** [yelusaleng/SAN_and_HDU-Net#1]
Hello,  I am the follower from the repository RRUnet, thanks for uploading the train data about your new work,i see the dataset contains about 8w pics,are the pics data augmented with the program in [this issue](https://github.com/yelusaleng/RRU-Net/issues/9)?Or the raw data need user to augment from 8w to about 30w?Thanks!

**Comment by Sh1p-wy** [comment]
hi,
san_8w is a dataset after data aug, you do not need to aug it agian.

**Comment by pokemonjs** [comment]
Thanks for your replying!Would you mind showing me the training options?I trained rrunet with my  RTX3060,which bs is 6 due to the Video Memory,so 50 epochs may take me about 24 hours while training in 2w dataset,if i use the 8w data,i will have only two chance to experiment one week,how many gpus did you use in the experiment?

**Comment by Sh1p-wy** [comment]
it's my pleasure.
i used 1 gpus RTX 3090 in these experiments.
does bs 6 fill your 3060?

**Comment by pokemonjs** [comment]
Sorry,I have replyed that day,but the comment is missing(maybe swallowed by server).I have tryed different bs,the largest bs 10 can fill the GPU memory,and the speed is almost the seam,it seems that lager bs not equals higher speed.Thanks for your suggestion!
