### ISSUE TITLE
关于论文

### ISSUE THREAD

**Issue by laichou** [yelusaleng/SAN_and_HDU-Net#4]
请问代码对应的论文在哪里可以看到？因为我暂时还查不到。

**Comment by Sh1p-wy** [comment]
https://onlinelibrary.wiley.com/doi/abs/10.1002/int.22939

**Comment by laichou** [comment]
这个下载完整的论文是要收费的是吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yelusaleng/SAN_and_HDU-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月2日(星期五) 上午8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yelusaleng/SAN_and_HDU-Net] 关于论文 (Issue #4)





 
https://onlinelibrary.wiley.com/doi/abs/10.1002/int.22939

**Comment by Sh1p-wy** [comment]
是，不过我可以发给你，你的邮箱是？

**Comment by laichou** [comment]
> 是，不过我可以发给你，你的邮箱是？

我的邮箱是：1041153443@qq.com，谢谢您了！
