### ISSUE TITLE
why i can not run it ?

### ISSUE THREAD

**Issue by XMUTer** [yelusaleng/SAN_and_HDU-Net#5]
please help me. i am freash .in my pycharm，it show : 
 File "E:\Anacondasave\envs\YOLO\lib\site-packages\kornia\augmentation\functional.py", line 488
    input = input.view((-1, (*input.shape[-3:])))
                             ^
SyntaxError: can't use starred expression here

could you tell me how to solve it ? thank you very much!

**Comment by Sh1p-wy** [comment]
sorry i can't help you about the issue.

**Comment by XMUTer** [comment]
> sorry i can't help you about the issue.

i can not run your code （inference.py）in pycharm.i meet many errors. could you send your code （can run）to my email ？ thank you very much！my email：704388761@qq.com

**Comment by Sh1p-wy** [comment]
关键我就是用这个代码正确运行的。
每台机器的配置环境，以及python库的版本都有可能引发错误，我无法帮你正确解决，这些错误你只能自己google解决

**Comment by XMUTer** [comment]
> 关键我就是用这个代码正确运行的。 每台机器的配置环境，以及python库的版本都有可能引发错误，我无法帮你正确解决，这些错误你只能自己google解决

OK，thank you very much.
