### ISSUE TITLE
The question of SAN training

### ISSUE THREAD

**Issue by gfgjs-139** [yelusaleng/SAN_and_HDU-Net#7]
Thanks for your code, I am trying to train my own model. Find the 74 lines of dataset. Py after mask = self.hwc_to_chw (mask), the following code will treat mask as a 3-channel image. But all the masks I found were single-channel images. Can you help me?

**Comment by Sh1p-wy** [comment]
don't worry, single channel will be converted to 3channels in the 88 line.
