### ISSUE TITLE
About the best_model.pth

### ISSUE THREAD

**Issue by llyxyi123456** [yelusaleng/SAN_and_HDU-Net#8]
Thank you for your code and dataset!
I ran it with your inference.py and best_model .There were problems with the model loading. I want the question if you changed the network.

RuntimeError: Error(s) in loading state_dict for Our:
	Missing key(s) in state_dict: "subnet_1.down.conv.conv1.0.weight", "subnet_1.down.conv.conv1.1.weight", "subnet_1.down.conv.conv1.1.bias", "subnet_1.down.conv.conv1.1.running_mean"......

Thank you very much if you can answer my questions！

**Comment by Sh1p-wy** [comment]
The network have been not changed.
Did you use several gpus to inference?

**Comment by llyxyi123456** [comment]
> The network have been not changed. Did you use several gpus to inference?

Thanks so much, I found the problem. I changed the code for using the GPU before.
